
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CUSTOMER_ADD_NEW : "CUSTOMER_ADD_NEW",
        CUSTOMER_EDIT : "CUSTOMER_EDIT",
        CUSTOMER_VIEW : "CUSTOMER_VIEW",
        CUSTOMER_CARD : "CUSTOMER_CARD",

        SUPPLIER_ADD_NEW : "SUPPLIER_ADD_NEW",
        SUPPLIER_EDIT : "SUPPLIER_EDIT",
        SUPPLIER_VIEW : "SUPPLIER_VIEW",
        SUPPLIER_CARD : "SUPPLIER_CARD",

        USER_ADD_NEW : "USER_ADD_NEW",
        USER_EDIT : "USER_EDIT",
        USER_VIEW : "USER_VIEW",
        USER_CARD : "USER_CARD",

        PAYMENT_ADD_NEW : "PAYMENT_ADD_NEW",
        PAYMENT_INVOICE : "PAYMENT_INVOICE",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
        CUSTOMER_FILTER : "CUSTOMER_FILTER",
        SUPPLIER_FILTER : "SUPPLIER_FILTER",
        USER_FILTER : "USER_FILTER",
        SALES_FILTER : "SALES_FILTER"
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        CUSTOMER_DELETE : "CUSTOMER_DELETE",
        SUPPLIER_DELETE : "SUPPLIER_DELETE",
        USER_DELETE : "USER_DELETE",
        SALES_DELETE : "SALES_DELETE",
        
    },
});
